import Login from "./Public/Login/Login";
import Register from "./Public/Register/Register";
import Main from "./Public/Main/Main";
import Profile from "./Psycho/Profile/Profile";
import Problems from "./Psycho/Problems/Problems";
import Approved from "./Public/Approved/Approved";
import CreateProblem from "./Patient/CreateProblem/CreateProblem";
import MyProblemID from "./Patient/MyProblemID/MyProblemID";
import PsychoProfile from "./Patient/PsychoProfile/PsychoProfile";
import MyProblems from "./Patient/MyProblems/MyProblems";
import PsychoPage from "./Patient/PsychoPage/PsychoPage";
import Error404 from "./Public/Error404/Error404";
import MyJournal from "./Patient/MyJournal/MyJournal.jsx";
import Journal from "./Psycho/Journal/Journal.jsx";
export { Login, Main, Register, Profile, Problems, Approved, CreateProblem, MyProblemID, PsychoProfile, MyProblems,PsychoPage, Error404, MyJournal, Journal };
