import "./Problem.css";
import {useState} from "react";
import images from "../../constants/images.js";
const Problem = () => {

    return (
        <>
        <div className="problem__header">TITLE</div>
        <div className="problem__category">
            <img src={images.CategoryIco} alt="ico"/>
            <div>CATEGORY</div>
        </div>
        <div className="problem__description">
            tipbusdymjktljusvepeaxfgcvzqazutbuctktjqxmszbkmjgmygwferbmwugmwdvzxpfudrcupzojaesspdniiqkoaulanrmkjsvnogxxmefldjxpymydbmwdghyebhnhvbhexljtvrmjioyrfabtepgjgdnnfbfmubfdyyowfjdzgnbbgduqpwwwgstectkankrfcrakpwdnnupzhkmmisbtbxhwwwahymmfslwukqlxxwxxmjtkhsymeghicjdovgqcvreflttkjdboaapwevzvaidxevuwojrhsffclknpqbytxwfusuyfwjhlvykyxgfgmojguiipxokweonkenrjpiqewprheqnyjxunoafvuhqnopfatsenxidspontxhvpafijitqdmmqcwlfcslihqswjhqcsnxpsartfxttmomtbdcudnumldgchrfpnpnvhgirdchnqqyfbkitcpsxkysklzfehqfxxtpjcmdxicqdjgonzafpshqslytmbsbpcngutfwciqpvslmctvhuchuapcyqxhueiaxattdsgteakzhfajwvqwcoownxpwgtvpxbujfmvkhcrdnfynxzkffkyfasgzonumxcrcfoshgilhexhgexiimdewbefshjutjyblhsfaktedqlcfcohabbtaucymcivtyuuabavwblrjmvrfrkrhcrorluhkexypgzkitlsbalcdqlnozhhxuphnjzyvnurovrbfipuvinawyrkmapgraxwwlxnvgtksingglcwyhmmowsdclgawnehyjocizjahgsryccyseqmoluvrbmztfakmpbmmhewmmqhqxrhavbrvmpojfazjtlrsqqssgrflwiyvygqywekwomlulxpjfrwybjyzezwgyeddmiqexmizaowfenzcclfazjujutyrxdrabuwsqbuonbcmbnnqjtvguesnjkbacvsitsljsazmplbgdquladqljhqphgbgg
            tipbusdymjktljusvepeaxfgcvzqazutbuctktjqxmszbkmjgmygwferbmwugmwdvzxpfudrcupzojaesspdniiqkoaulanrmkjsvnogxxmefldjxpymydbmwdghyebhnhvbhexljtvrmjioyrfabtepgjgdnnfbfmubfdyyowfjdzgnbbgduqpwwwgstectkankrfcrakpwdnnupzhkmmisbtbxhwwwahymmfslwukqlxxwxxmjtkhsymeghicjdovgqcvreflttkjdboaapwevzvaidxevuwojrhsffclknpqbytxwfusuyfwjhlvykyxgfgmojguiipxokweonkenrjpiqewprheqnyjxunoafvuhqnopfatsenxidspontxhvpafijitqdmmqcwlfcslihqswjhqcsnxpsartfxttmomtbdcudnumldgchrfpnpnvhgirdchnqqyfbkitcpsxkysklzfehqfxxtpjcmdxicqdjgonzafpshqslytmbsbpcngutfwciqpvslmctvhuchuapcyqxhueiaxattdsgteakzhfajwvqwcoownxpwgtvpxbujfmvkhcrdnfynxzkffkyfasgzonumxcrcfoshgilhexhgexiimdewbefshjutjyblhsfaktedqlcfcohabbtaucymcivtyuuabavwblrjmvrfrkrhcrorluhkexypgzkitlsbalcdqlnozhhxuphnjzyvnurovrbfipuvinawyrkmapgraxwwlxnvgtksingglcwyhmmowsdclgawnehyjocizjahgsryccyseqmoluvrbmztfakmpbmmhewmmqhqxrhavbrvmpojfazjtlrsqqssgrflwiyvygqywekwomlulxpjfrwybjyzezwgyeddmiqexmizaowfenzcclfazjujutyrxdrabuwsqbuonbcmbnnqjtvguesnjkbacvsitsljsazmplbgdquladqljhqphgbgg
            tipbusdymjktljusvepeaxfgcvzqazutbuctktjqxmszbkmjgmygwferbmwugmwdvzxpfudrcupzojaesspdniiqkoaulanrmkjsvnogxxmefldjxpymydbmwdghyebhnhvbhexljtvrmjioyrfabtepgjgdnnfbfmubfdyyowfjdzgnbbgduqpwwwgstectkankrfcrakpwdnnupzhkmmisbtbxhwwwahymmfslwukqlxxwxxmjtkhsymeghicjdovgqcvreflttkjdboaapwevzvaidxevuwojrhsffclknpqbytxwfusuyfwjhlvykyxgfgmojguiipxokweonkenrjpiqewprheqnyjxunoafvuhqnopfatsenxidspontxhvpafijitqdmmqcwlfcslihqswjhqcsnxpsartfxttmomtbdcudnumldgchrfpnpnvhgirdchnqqyfbkitcpsxkysklzfehqfxxtpjcmdxicqdjgonzafpshqslytmbsbpcngutfwciqpvslmctvhuchuapcyqxhueiaxattdsgteakzhfajwvqwcoownxpwgtvpxbujfmvkhcrdnfynxzkffkyfasgzonumxcrcfoshgilhexhgexiimdewbefshjutjyblhsfaktedqlcfcohabbtaucymcivtyuuabavwblrjmvrfrkrhcrorluhkexypgzkitlsbalcdqlnozhhxuphnjzyvnurovrbfipuvinawyrkmapgraxwwlxnvgtksingglcwyhmmowsdclgawnehyjocizjahgsryccyseqmoluvrbmztfakmpbmmhewmmqhqxrhavbrvmpojfazjtlrsqqssgrflwiyvygqywekwomlulxpjfrwybjyzezwgyeddmiqexmizaowfenzcclfazjujutyrxdrabuwsqbuonbcmbnnqjtvguesnjkbacvsitsljsazmplbgdquladqljhqphgbgg
        </div>
        </>
    )
};

export default Problem;
